// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error)
	CreateSessionCycle(ctx context.Context, arg CreateSessionCycleParams) (int64, error)
	CreateTimeProfile(ctx context.Context, arg CreateTimeProfileParams) (TimeProfile, error)
	DeleteSession(ctx context.Context, id int64) error
	DeleteSessionCycle(ctx context.Context, id int64) error
	DeleteTimeProfile(ctx context.Context, id int64) error
	GetDefaultTimeProfile(ctx context.Context) (TimeProfile, error)
	GetSessionById(ctx context.Context, id int64) (Session, error)
	GetSessionCycleByID(ctx context.Context, id int64) (SessionCycle, error)
	GetSessionCycleByStatusWithMetadata(ctx context.Context, status sql.NullString) ([]GetSessionCycleByStatusWithMetadataRow, error)
	GetTimeProfile(ctx context.Context, id int64) (TimeProfile, error)
	ListSessionCycles(ctx context.Context, arg ListSessionCyclesParams) ([]SessionCycle, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	ListTimeProfiles(ctx context.Context) ([]TimeProfile, error)
	MarkSessionCompleted(ctx context.Context, id int64) error
	MarkSessionCycleComplete(ctx context.Context, arg MarkSessionCycleCompleteParams) error
	MarkSessionCycleCompleted(ctx context.Context, id int64) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateSessionCycleStatus(ctx context.Context, arg UpdateSessionCycleStatusParams) error
	UpdateSessionNote(ctx context.Context, arg UpdateSessionNoteParams) error
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
	UpdateTimeProfile(ctx context.Context, arg UpdateTimeProfileParams) (TimeProfile, error)
}

var _ Querier = (*Queries)(nil)
