// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error)
	CreateSessionCycle(ctx context.Context, arg CreateSessionCycleParams) (int64, error)
	DeleteSession(ctx context.Context, id int64) error
	DeleteSessionCycle(ctx context.Context, id int64) error
	GetActiveSessions(ctx context.Context) ([]Session, error)
	GetAllSessions(ctx context.Context) ([]Session, error)
	GetCompletedSessions(ctx context.Context) ([]Session, error)
	GetLatestSessionCycleByStatus(ctx context.Context, status sql.NullString) (SessionCycle, error)
	GetSessionById(ctx context.Context, id int64) (Session, error)
	GetSessionCycleByID(ctx context.Context, id int64) (SessionCycle, error)
	GetSessionCycleByStatusWithMetadata(ctx context.Context, status sql.NullString) ([]GetSessionCycleByStatusWithMetadataRow, error)
	GetSessionCyclesBySessionID(ctx context.Context, sessionID int64) ([]SessionCycle, error)
	GetSessionCyclesByStatus(ctx context.Context, status sql.NullString) ([]SessionCycle, error)
	GetSessionCyclesByType(ctx context.Context, type_ sql.NullString) ([]SessionCycle, error)
	GetSessionsByTrackedStatus(ctx context.Context, isTracked sql.NullBool) ([]Session, error)
	GetSessionsForDate(ctx context.Context, createdAt sql.NullTime) ([]Session, error)
	MarkSessionCompleted(ctx context.Context, id int64) error
	MarkSessionCycleComplete(ctx context.Context, arg MarkSessionCycleCompleteParams) error
	MarkSessionCycleCompleted(ctx context.Context, id int64) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateSessionCycleStatus(ctx context.Context, arg UpdateSessionCycleStatusParams) error
	UpdateSessionEndTime(ctx context.Context, arg UpdateSessionEndTimeParams) error
	UpdateSessionNote(ctx context.Context, arg UpdateSessionNoteParams) error
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
}

var _ Querier = (*Queries)(nil)
