// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (label, note, status, session_estimate, is_tracked)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id
`

type CreateSessionParams struct {
	Label           string
	Note            sql.NullString
	Status          string
	SessionEstimate sql.NullInt64
	IsTracked       sql.NullBool
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.Label,
		arg.Note,
		arg.Status,
		arg.SessionEstimate,
		arg.IsTracked,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getActiveSessions = `-- name: GetActiveSessions :many
SELECT id, label, status, session_estimate, is_tracked, note, created_at, updated_at FROM sessions WHERE status = 'running'
`

func (q *Queries) GetActiveSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Status,
			&i.SessionEstimate,
			&i.IsTracked,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSessions = `-- name: GetAllSessions :many
SELECT id, label, status, session_estimate, is_tracked, note, created_at, updated_at FROM sessions ORDER BY created_at DESC
`

func (q *Queries) GetAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Status,
			&i.SessionEstimate,
			&i.IsTracked,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedSessions = `-- name: GetCompletedSessions :many
SELECT id, label, status, session_estimate, is_tracked, note, created_at, updated_at FROM sessions WHERE status = 'completed' ORDER BY updated_at DESC
`

func (q *Queries) GetCompletedSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Status,
			&i.SessionEstimate,
			&i.IsTracked,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, label, status, session_estimate, is_tracked, note, created_at, updated_at FROM sessions WHERE id = ?1
`

func (q *Queries) GetSessionById(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Status,
		&i.SessionEstimate,
		&i.IsTracked,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionsByTrackedStatus = `-- name: GetSessionsByTrackedStatus :many
SELECT id, label, status, session_estimate, is_tracked, note, created_at, updated_at FROM sessions WHERE is_tracked = ?1 ORDER BY created_at DESC
`

func (q *Queries) GetSessionsByTrackedStatus(ctx context.Context, isTracked sql.NullBool) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByTrackedStatus, isTracked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Status,
			&i.SessionEstimate,
			&i.IsTracked,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsForDate = `-- name: GetSessionsForDate :many
SELECT id, label, status, session_estimate, is_tracked, note, created_at, updated_at FROM sessions WHERE DATE(created_at) = ?1
`

func (q *Queries) GetSessionsForDate(ctx context.Context, createdAt sql.NullTime) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsForDate, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Status,
			&i.SessionEstimate,
			&i.IsTracked,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionCompleted = `-- name: MarkSessionCompleted :exec
UPDATE sessions
SET status = 'completed'
WHERE id = ?1
`

func (q *Queries) MarkSessionCompleted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markSessionCompleted, id)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET label = ?2,
    note = ?3,
    status = ?4,
    session_estimate = ?5,
    is_tracked = ?6
WHERE id = ?1
`

type UpdateSessionParams struct {
	ID              int64
	Label           string
	Note            sql.NullString
	Status          string
	SessionEstimate sql.NullInt64
	IsTracked       sql.NullBool
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.ID,
		arg.Label,
		arg.Note,
		arg.Status,
		arg.SessionEstimate,
		arg.IsTracked,
	)
	return err
}

const updateSessionNote = `-- name: UpdateSessionNote :exec
UPDATE sessions SET note = ?2 WHERE id = ?1
`

type UpdateSessionNoteParams struct {
	ID   int64
	Note sql.NullString
}

func (q *Queries) UpdateSessionNote(ctx context.Context, arg UpdateSessionNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionNote, arg.ID, arg.Note)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions SET status = ?2 WHERE id = ?1
`

type UpdateSessionStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.ID, arg.Status)
	return err
}
