// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: time_profiles.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTimeProfile = `-- name: CreateTimeProfile :one
INSERT INTO time_profiles (
  name, 
  work_duration, 
  break_duration, 
  long_break_duration, 
  long_break_cycle,
  is_default
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, name, work_duration, break_duration, long_break_duration, long_break_cycle, is_default
`

type CreateTimeProfileParams struct {
	Name              string
	WorkDuration      int64
	BreakDuration     int64
	LongBreakDuration int64
	LongBreakCycle    sql.NullInt64
	IsDefault         sql.NullBool
}

func (q *Queries) CreateTimeProfile(ctx context.Context, arg CreateTimeProfileParams) (TimeProfile, error) {
	row := q.db.QueryRowContext(ctx, createTimeProfile,
		arg.Name,
		arg.WorkDuration,
		arg.BreakDuration,
		arg.LongBreakDuration,
		arg.LongBreakCycle,
		arg.IsDefault,
	)
	var i TimeProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkDuration,
		&i.BreakDuration,
		&i.LongBreakDuration,
		&i.LongBreakCycle,
		&i.IsDefault,
	)
	return i, err
}

const deleteTimeProfile = `-- name: DeleteTimeProfile :exec
DELETE FROM time_profiles
WHERE id = ?
`

func (q *Queries) DeleteTimeProfile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTimeProfile, id)
	return err
}

const getDefaultTimeProfile = `-- name: GetDefaultTimeProfile :one
SELECT id, name, work_duration, break_duration, long_break_duration, long_break_cycle, is_default FROM time_profiles
WHERE is_default = true LIMIT 1
`

func (q *Queries) GetDefaultTimeProfile(ctx context.Context) (TimeProfile, error) {
	row := q.db.QueryRowContext(ctx, getDefaultTimeProfile)
	var i TimeProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkDuration,
		&i.BreakDuration,
		&i.LongBreakDuration,
		&i.LongBreakCycle,
		&i.IsDefault,
	)
	return i, err
}

const getTimeProfile = `-- name: GetTimeProfile :one
SELECT id, name, work_duration, break_duration, long_break_duration, long_break_cycle, is_default FROM time_profiles
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTimeProfile(ctx context.Context, id int64) (TimeProfile, error) {
	row := q.db.QueryRowContext(ctx, getTimeProfile, id)
	var i TimeProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkDuration,
		&i.BreakDuration,
		&i.LongBreakDuration,
		&i.LongBreakCycle,
		&i.IsDefault,
	)
	return i, err
}

const listTimeProfiles = `-- name: ListTimeProfiles :many
SELECT id, name, work_duration, break_duration, long_break_duration, long_break_cycle, is_default FROM time_profiles
ORDER BY name
`

func (q *Queries) ListTimeProfiles(ctx context.Context) ([]TimeProfile, error) {
	rows, err := q.db.QueryContext(ctx, listTimeProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeProfile
	for rows.Next() {
		var i TimeProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkDuration,
			&i.BreakDuration,
			&i.LongBreakDuration,
			&i.LongBreakCycle,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeProfile = `-- name: UpdateTimeProfile :one
UPDATE time_profiles
SET 
  name = ?,
  work_duration = ?,
  break_duration = ?,
  long_break_duration = ?,
  long_break_cycle = ?,
  is_default = ?
WHERE id = ?
RETURNING id, name, work_duration, break_duration, long_break_duration, long_break_cycle, is_default
`

type UpdateTimeProfileParams struct {
	Name              string
	WorkDuration      int64
	BreakDuration     int64
	LongBreakDuration int64
	LongBreakCycle    sql.NullInt64
	IsDefault         sql.NullBool
	ID                int64
}

func (q *Queries) UpdateTimeProfile(ctx context.Context, arg UpdateTimeProfileParams) (TimeProfile, error) {
	row := q.db.QueryRowContext(ctx, updateTimeProfile,
		arg.Name,
		arg.WorkDuration,
		arg.BreakDuration,
		arg.LongBreakDuration,
		arg.LongBreakCycle,
		arg.IsDefault,
		arg.ID,
	)
	var i TimeProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkDuration,
		&i.BreakDuration,
		&i.LongBreakDuration,
		&i.LongBreakCycle,
		&i.IsDefault,
	)
	return i, err
}
